name = "lean-stlc"
version = "0.1.0"
defaultTargets = ["lean-stlc"]

[[require]]
name = "lean-subst"
scope = "arthur-adjedj"
git = "https://github.com/arthur-adjedj/lean-subst"
rev = "4.32.0-rc1"

[[require]]
name = "aesop"
scope = "leanprover-community"
git = "https://github.com/leanprover-community/aesop"
rev = "master"

[[require]]
name = "LeanALaCarte"
scope = "leanprover-community"
git = "https://github.com/arthur-adjedj/LeanALaCarte"
rev = "d2d90d8d08e2056a277f5ac69b3ed3f4c6cd8680"

[[lean_lib]]
name = "LeanStlc"

[[lean_exe]]
name = "lean-stlc"
root = "Main"
