name = "lean-stlc"
version = "0.1.0"
defaultTargets = ["lean-stlc"]

[[require]]
name = "lean-subst"
scope = "arthur-adjedj"
git = "https://github.com/arthur-adjedj/lean-subst"
rev = "4.32.0-rc1"

[[require]]
name = "aesop"
scope = "leanprover-community"
git = "https://github.com/leanprover-community/aesop"
rev = "master"

# TODO put real git dependency once the project gets stable enough
[[require]]
name = "LeanALaCarte"
path = "/home/belazy/Documents/LeanALaCarte"

[[lean_lib]]
name = "LeanStlc"

[[lean_exe]]
name = "lean-stlc"
root = "Main"
